<footer class="clearfix"><!-- Defining the footer section of the page -->
  <section id="privacy">
    Raul Sitta &copy; 2024 <a class="link" href="http://www.unife.it/">Universit&agrave; degli Studi di Ferrara</a><br />
    <a class="link" href="https://unife.coursecatalogue.cineca.it/insegnamenti/2023/8520/2018/2/10533?annoOrdinamento=2018&coorte=2021">Ingegneria del Software</a>
  </section>
</footer>